services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: faithadmin
      POSTGRES_PASSWORD: faithpass
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"

  user-service:
    build: ./user-service
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/userdb
      - JWT_SECRET=your_jwt_secret
      - MONITORING_URL=http://monitoring-service:4002/api/logs
    depends_on:
      - mongo

  finance-service:
    build: ./finance-service
    ports:
      - "3002:3000"
    environment:
      - PG_URI=postgres://faithadmin:faithpass@postgres:5432/finance_db
    depends_on:
      - postgres

  monitoring-service:
    build: ./monitoring-service
    ports:
      - "4002:4002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/monitoring
      - JWT_SECRET=your_jwt_secret
      - PORT=4002
    depends_on:
      - mongo
