services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"

  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/userdb
      - JWT_SECRET=supersecret
      - MONITORING_SERVICE_URL=http://monitoring-service:3003/api/logs
    depends_on:
      - mongo
      - monitoring-service

  finance-service:
    build: ./finance-service
    ports:
      - "3002:3002"
    environment:
      - DB_NAME=finance_db
      - DB_USER=postgres
      - DB_PASS=pass123
      - DB_HOST=postgres
      - MONITORING_SERVICE_URL=http://monitoring-service:3003/api/logs
      - JWT_SECRET=supersecret
    depends_on:
      - postgres

  monitoring-service:
    build: ./monitoring-service
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/monitoring
      - JWT_SECRET=supersecret
      - PORT=3003
    depends_on:
      - mongo
