apiVersion: v1
kind: Service
metadata:
  name: finance-service
  labels:
    app: finance-service
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: finance-service
