apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-service
  template:
    metadata:
      labels:
        app: finance-service
    spec:
      containers:
        - name: finance-service
          image: delacruzjeremy/church-finance-app-finance-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: finance-service-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: finance-service-config
                  key: DB_USER
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: finance-service-config
                  key: DB_HOST
            - name: MONITORING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: finance-service-config
                  key: MONITORING_SERVICE_URL
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: finance-service-secret
                  key: DB_PASS
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: finance-service-secret
                  key: JWT_SECRET
