apiVersion: v1
kind: Service
metadata:
  name: report-service
  labels:
    app: report-service
spec:
  type: NodePort
  ports:
    - port: 3002
      targetPort: 3002
  selector:
    app: report-service
