apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  labels:
    app: monitoring-service
spec:
  type: NodePort
  ports:
    - port: 3003
      targetPort: 3003
  selector:
    app: monitoring-service
