apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  labels:
    app: user-service
data:
  PORT: "3000"
  MONGO_URI: "mongodb://mongo:27017/user-servicedb"
  MONITORING_SERVICE_URL: "http://monitoring-service:3003/api/logs"
