name: FaithFinance CI/CD

on:
  push:
    branches:
      - main
      - feature-finance-service
  pull_request:
    branches:
      - main
      - feature-finance-service

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: finance_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pass123
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      MONGO_URI: mongodb://localhost:27017/userdb_test
      JWT_SECRET: supersecret
      MONITORING_SERVICE_URL: http://localhost:31739/api/logs
      DB_NAME: finance_db
      DB_USER: postgres
      DB_PASS: pass123
      DB_HOST: localhost
      CI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (User Service)
        working-directory: ./user-service
        run: npm install

      - name: Run tests (User Service)
        working-directory: ./user-service
        run: npm test
      
      - name: Install dependencies (Monitoring Service)
        working-directory: ./monitoring-service
        run: npm ci

      - name: Run tests (Monitoring Service)
        working-directory: ./monitoring-service
        run: npm test

      - name: Install dependencies (Finance Service)
        working-directory: ./finance-service
        run: npm ci

      - name: Run tests (Finance Service)
        working-directory: ./finance-service
        run: npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image (user-service)
        run: |
          docker build -t delacruzjeremy/church-finance-app-user-service:latest ./user-service
          docker push delacruzjeremy/church-finance-app-user-service:latest

      - name: Build and push Docker image (monitoring-service)
        run: |
          docker build -t delacruzjeremy/church-finance-app-monitoring-service:latest ./monitoring-service
          docker push delacruzjeremy/church-finance-app-monitoring-service:latest

      - name: Build and push Docker image (finance-service)
        run: |
          docker build -t delacruzjeremy/church-finance-app-finance-service:latest ./finance-service
          docker push delacruzjeremy/church-finance-app-finance-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubeconfig for K3s (AWS VM)
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA_B64 }}" | base64 -d > $HOME/.kube/config
      
      - name: Verify Kubernetes connection
        run: |
          kubectl config current-context
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy MongoDB
        run: |
          kubectl apply -f k8s-infra/mongo-deployment.yaml

      - name: Wait for MongoDB to be ready
        run: |
          kubectl wait --for=condition=ready pod -l app=mongo --timeout=60s

      - name: Deploy User Service
        run: |
          kubectl apply -f user-service/k8s/user-service-configmap.yaml
          kubectl apply -f user-service/k8s/user-service-secret.yaml
          kubectl apply -f user-service/k8s/user-service-deployment.yaml
          kubectl apply -f user-service/k8s/user-service-service.yaml
          kubectl apply -f user-service/k8s/user-service-hpa.yaml
      
      - name: Deploy Monitoring Service
        run: |
          kubectl apply -f monitoring-service/k8s/monitoring-service-configmap.yaml
          kubectl apply -f monitoring-service/k8s/monitoring-service-secret.yaml
          kubectl apply -f monitoring-service/k8s/monitoring-service-deployment.yaml
          kubectl apply -f monitoring-service/k8s/monitoring-service-service.yaml
          kubectl apply -f monitoring-service/k8s/monitoring-service-hpa.yaml

      - name: Deploy Finance Service
        run: |
          kubectl apply -f finance-service/k8s/finance-service-configmap.yaml
          kubectl apply -f finance-service/k8s/finance-service-secret.yaml
          kubectl apply -f finance-service/k8s/finance-service-deployment.yaml
          kubectl apply -f finance-service/k8s/finance-service-service.yaml

      - name: Verify deployments
        run: kubectl get pods -o wide
